bug fix

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -19,11 +19,23 @@ jobs:
 
     - name: SSH and Deploy with Retry
       run: |
-        ssh -o StrictHostKeyChecking=no root@106.15.139.48 << EOF
+        ssh -o StrictHostKeyChecking=no root@106.15.139.48 << 'EOF'
           cd server
           git stash
           git stash drop
-          git pull
+          retry=3
+          delay=10
+          until [[ $retry -le 0 ]]
+          do
+            git pull && break
+            retry=$((retry-1))
+            echo "Pull failed, retrying in $delay seconds..."
+            sleep $delay
+          done
+          if [[ $retry -le 0 ]]; then
+            echo "Git pull failed after multiple attempts."
+            exit 1
+          fi
           chmod +x ./deploy.sh
           ./deploy.sh restart
         EOF
