try connection between server

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -9,33 +9,33 @@ jobs:
   deploy:
     runs-on: ubuntu-latest
     steps:
-    - name: Checkout repository
-      uses: actions/checkout@v3
+      - name: Checkout repository
+        uses: actions/checkout@v3
 
-    - name: Set up SSH
-      uses: webfactory/ssh-agent@v0.6.0
-      with:
-        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
+      - name: Set up SSH
+        uses: webfactory/ssh-agent@v0.6.0
+        with:
+          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
 
-    - name: SSH and Deploy with Retry
-      run: |
-        ssh -o StrictHostKeyChecking=no root@106.15.139.48 << 'EOF'
-          cd server
-          git stash
-          git stash drop
-          retry=3
-          delay=10
-          until [[ $retry -le 0 ]]
-          do
-            git pull && break
-            retry=$((retry-1))
-            echo "Pull failed, retrying in $delay seconds..."
-            sleep $delay
-          done
-          if [[ $retry -le 0 ]]; then
-            echo "Git pull failed after multiple attempts."
-            exit 1
-          fi
-          chmod +x ./deploy.sh
-          ./deploy.sh restart
-        EOF
+      - name: SSH and Deploy with Retry
+        run: |
+          ssh -o StrictHostKeyChecking=no root@106.15.139.48 << 'EOF'
+            cd server
+            git stash
+            git stash drop
+            retry=3
+            delay=10
+            until [[ $retry -le 0 ]]
+            do
+              git pull && break
+              retry=$((retry-1))
+              echo "Pull failed, retrying in $delay seconds..."
+              sleep $delay
+            done
+            if [[ $retry -le 0 ]]; then
+              echo "Git pull failed after multiple attempts."
+              exit 1
+            fi
+            chmod +x ./deploy.sh
+            ./deploy.sh restart
+          EOF
